name: Test and Lint

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test-and-lint-front-end:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
